### ISSUE TITLE
'ember g ember-cli-foundation-sass' not working on io.js 1.2.0

### ISSUE THREAD

**Issue by chrisbenson** [artificialio/ember-cli-foundation-sass#20]
When using **io.js v1.2.0**, I am unable to get past this point on a brand new Ember.js app with only ember-cli-foundation-sass installed.  After researching a bit, it seems that this was caused by node-sass, but that it has already been fixed upstream.  I'm not sure how to make ember-cli-foundation-sass use node-sass 2.0.1 rather than node-sass 1.2.3, since node-sass is not listed as a dependency in package.json.  Thank you.

- https://github.com/sass/node-sass-binaries/releases/tag/v2.0.0
- https://github.com/sass/node-sass/issues/655
- https://github.com/sass/node-sass/issues/627

```
$ ember g ember-cli-foundation-sass
version: 0.1.15
installing
Installing browser packages via Bower...
  cached git://github.com/zurb/bower-foundation.git#5.5.1
  cached git://github.com/jquery/jquery.git#2.1.3
  cached git://github.com/carhartl/jquery-cookie.git#1.4.1
  cached git://github.com/Modernizr/Modernizr.git#2.8.3
  cached git://github.com/ftlabs/fastclick.git#1.0.6
  cached git://github.com/mathiasbynens/jquery-placeholder.git#2.0.9
  cached git://github.com/jquery/jquery.git#2.1.3
  conflict Unable to find suitable version for jquery
    1) jquery ^1.11.1
    2) jquery >=1.2
    3) jquery >=1.6
    4) jquery >= 2.1.0
    5) jquery >= 1.7.0 < 2.2.0
[?] Answer: 1
Installed browser packages via Bower.
  create app/styles/app.scss
  install packages ember-cli-sass, broccoli-clean-css
Installing packages for tooling via npm.Binary downloaded and installed at /Users/Chris/code/ember/leader-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/vendor/darwin-x64/binding.node
`darwin-x64` exists; testing
module.js:341
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
    at Module.require (module.js:351:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/Users/Chris/code/ember/leader-web/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:446:26)
    at Object.Module._extensions..js (module.js:464:10)
    at Module.load (module.js:341:32)
    at Function.Module._load (module.js:296:12)
node-sass@1.2.3 postinstall: `node scripts/build.js`
Exit status 1
Error: node-sass@1.2.3 postinstall: `node scripts/build.js`
Exit status 1
    at EventEmitter.<anonymous> (/Users/Chris/code/ember/leader-web/node_modules/ember-cli/node_modules/npm/lib/utils/lifecycle.js:212:16)
    at emitTwo (events.js:85:13)
    at EventEmitter.emit (events.js:153:7)
    at ChildProcess.<anonymous> (/Users/Chris/code/ember/leader-web/node_modules/ember-cli/node_modules/npm/lib/utils/spawn.js:14:12)
    at emitTwo (events.js:85:13)
    at ChildProcess.emit (events.js:153:7)
    at maybeClose (child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
```

**Comment by Globegitter** [comment]
Unfortunately the problem is middlestream so to speak: https://github.com/joliss/broccoli-sass/pull/43
If you change your package.json to `"ember-cli-sass": "aexmachina/ember-cli-sass#sources-content"` you might be able to get it to work.

**Comment by Globegitter** [comment]
Should also be working with ember-cli-sass 3.1.0-beta.5. Will update asap, or also happily accept a pr.

**Comment by Globegitter** [comment]
@chrisbenson check the latest master version - should now work. Will publish a new version soon.

**Comment by Globegitter** [comment]
Should be working with both `1.0.1` as well as `1.1.0`.

**Comment by izumeroot** [comment]
Hello! Can you help with same problem..

ember install:addon ember-cli-foundation-sass                                                                   ⬡ 5.1.0 [±master]
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
This command has been deprecated. Please use `ember install <addonName>` instead.
Installed packages for tooling via npm.
installing ember-cli-foundation-sass
  install bower package foundation
Installing browser packages via Bower...
  cached git://github.com/zurb/bower-foundation.git#5.5.3
  cached git://github.com/jquery/jquery.git#2.1.4
  cached git://github.com/jquery/jquery.git#1.11.3
  cached git://github.com/jquery/jquery.git#2.1.4
  cached git://github.com/jquery/jquery.git#2.1.4
  conflict Unable to find suitable version for jquery
    1) jquery >= 1.7.0 < 2.2.0
    2) jquery ^1.11.3
    3) jquery >= 2.1.0
    4) jquery >=1.2
    5) jquery >=1.6
[?] Answer: 2
Installed browser packages via Bower.
  create app/styles/app.scss
  install packages ember-cli-sass, broccoli-clean-css
Installing packages for tooling via npmCan not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-5.1/binding.node
Installing packages for tooling via npm.module.js:340
    throw err;
    ^

Error: Cannot find module '/home/igor/projects/extending-todomvc/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/node_modules/pangyp/bin/node-gyp'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
Build failed
Installed packages for tooling via npm.
Installed addon package.
                                                                                                                                      
igor@hp-laptop ~/projects/extending-todomvc                                                                                 [9:16:22] 
> $ ember s                                                                                                      ⬡ 5.1.0 [±master ●●]
`libsass` bindings not found. Try reinstalling `node-sass`?
Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/igor/projects/extending-todomvc/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/igor/projects/extending-todomvc/node_modules/ember-cli-sass/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/igor/projects/extending-todomvc/node_modules/ember-cli-sass/node_modules/broccoli-sass/index.js:5:12)
    at Module._compile (module.js:425:26)

**Comment by izumeroot** [comment]
I see in previous console log:

>Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/linux-x64-node-5.1/binding.node

I have downgraded nodejs to version 0.12.8 and instead this error i have seen

>Installing packages for tooling via npm...linux-x64-node-0.12 exists; testing

It works now.

Look like it does not work with nodejs 5.1.0
